apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zrux8ddlc-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe-java-quarkus:c9e36d849e9ed28eec934256d8e15a201a3d9e6d@sha256:6e26f0ada3e3e1f29b81bc5b132a7fbae0b92851c4cda2465f2e73b7cf6bbe86
          name: container-image
