apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zrux8ddlc-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe-java-quarkus:e4434327c900008de46e76728bd107515d1d74e9@sha256:b539260ec75f5d2665a035122f286e17fc422c63c980e80a3ecdb41e0e5ff0b5
          name: container-image
